name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Starting server for curl test
      run: nohup ./multiproxy https://www.rust-lang.org/ https://hmpioneers.net/hockey/ &

    - name: Get content from 1st website
      run: curl -f -s "http://0.0.0.0:8888/learn" | grep "Rust"
      
    - name: Get content from 2nd website
      run: curl -f -s "http://0.0.0.0:8888/history.htm" | grep "Hill-Murray"
